//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Layer_Front
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMATRICULA
    {
        public decimal IDMATRICULA { get; set; }
        public decimal IDCURSO { get; set; }
        public Nullable<decimal> IDSECCION { get; set; }
        public Nullable<decimal> VACANTES { get; set; }
        public string DNI { get; set; }
        public string TIPOMATRICULA { get; set; }
        public Nullable<System.DateTime> REGMATRICULATIME { get; set; }
        public Nullable<System.DateTime> ANULMATRICULATIME { get; set; }
        public string ESTADO { get; set; }
    }
}
