//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Layer_Front
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSECCION
    {
        public decimal IDSECCION { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
    }
}
