//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Layer_Front
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitySolo : DbContext
    {
        public EntitySolo()
            : base("name=EntitySolo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBALUMNOS> TBALUMNOS { get; set; }
        public virtual DbSet<TBCURSOS> TBCURSOS { get; set; }
        public virtual DbSet<TBMATRICULA> TBMATRICULA { get; set; }
        public virtual DbSet<TBSECCION> TBSECCION { get; set; }
        public virtual DbSet<TBVACANTES> TBVACANTES { get; set; }
    }
}
